#
# Run all checks on PRs and pushes
#
name: Checks

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main, next, beta, alpha]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-pr:
    name: '📌'
    uses: ./.github/workflows/lint-pr.yml
    permissions:
      contents: read
      packages: read

  lint-code:
    name: '📌'
    needs: [lint-pr]
    uses: ./.github/workflows/lint-code.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
    permissions:
      contents: read
      issues: read
      pull-requests: write
